{application,project2,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"project2"},
              {modules,['Elixir.Loop','Elixir.Loop2','Elixir.Loop3',
                        'Elixir.Loop3D_1','Elixir.Loop3D_2','Elixir.Loop3D_3',
                        'Elixir.Loop_kill','Elixir.Loop_nextnode',
                        'Elixir.Project2','Elixir.Project2.Loop_con']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
